authenicate/urls.py
from django.urls import path

from authenicate.views import Login, Register, Logout

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
]

catalogue/urls.py
from django.urls import path

from catalogue.views import Products, ProductCreate, ProductUpdate, ProductDelete, PurchaseCreate, PurchaseError, \
    PurchaseList, ReturnCreate

urlpatterns = [
    path('', Products.as_view(), name="list"),
    path('product/create/', ProductCreate.as_view(), name="product_create"),
    path('product/update/<int:pk>/', ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name="product_delete"),
    path('product/bay/<int:pk>/', PurchaseCreate.as_view(), name='purchase_create'),
    path('purchase/error/', PurchaseError.as_view(), name='purchase_error'),
    path('purchase/list/', PurchaseList.as_view(), name='purchase_list'),
    path('return/create/', ReturnCreate.as_view(), name='return_create')
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('authenicate.urls')),
    path('', include('catalogue.urls')),
]

authenicate/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class MyUser(AbstractUser):
    cash = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        default=10000.00,
        validators=[MinValueValidator(Decimal('0.00'))]
    )

catalogue/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from authenicate.models import MyUser


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10000)
    storage = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'id': self.id})


class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    buyer = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    total_cost = models.DecimalField(decimal_places=2, max_digits=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    return_goods = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.buyer.username} BUY {self.product.title} ({self.quantity}) IN {self.created_at}"


class Return(models.Model):
    purchase = models.OneToOneField(Purchase, on_delete=models.CASCADE)

authenicate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from authenicate.models import MyUser


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254)

    class Meta:
        model = MyUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

catalogue/forms.py
from django.forms import ModelForm

from catalogue.models import Product, Purchase, Return


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'price', 'storage')


class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = ('quantity',)


class Reclamation(ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'


class ReturnForm(ModelForm):
    class Meta:
        model = Return
        fields = '__all__'

authenicate/views.py
from django.contrib.auth.views import LoginView, LogoutView


# Create your views here.
from django.shortcuts import redirect
from django.views.generic import CreateView

from authenicate.forms import RegisterForm
from authenicate.models import MyUser


class Login(LoginView):
    http_method_names = ['get', 'post']
    redirect_authenticated_user = True
    template_name = 'authenticate/login.html'


class Logout(LogoutView):
    http_method_names = ['get']
    template_name = 'authenticate/logout.html'

    def get(self, *args, **kwargs):
        super().get(*args, **kwargs)
        return redirect('list')


class Register(CreateView):
    model = MyUser
    form_class = RegisterForm
    template_name = 'authenticate/register.html'
    success_url = '/'

catalogue/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView, TemplateView, UpdateView
from datetime import timedelta

from django.utils import timezone

from catalogue.forms import ProductForm, PurchaseForm, ReturnForm
from catalogue.models import Product, Purchase, Return
from authenicate.models import MyUser


class Products(ListView):
    model = Product
    template_name = 'list/index.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'buy_form': PurchaseForm
        })
        return context


class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    http_method_names = ['get', 'post']
    success_url = '/create/'
    form_class = ProductForm
    template_name = 'list/product_create.html'


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = 'list/product_update.html'
    success_url = '/'
    form_class = ProductForm


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    http_method_names = ['post']
    success_url = '/'


class PurchaseCreate(LoginRequiredMixin, CreateView):
    model = Purchase
    http_method_names = ['post']
    success_url = '/'
    form_class = PurchaseForm
    template_name = 'list/purchase_create.html'

    def form_valid(self, form):
        form_add = form.save(commit=False)
        form_add.buyer_id = self.request.user.pk
        form_add.product_id = self.kwargs['pk']
        form_add.total_cost = form.instance.product.price * form.cleaned_data['quantity']
        user = MyUser.objects.get(pk=form_add.buyer_id)
        user.cash -= form_add.total_cost
        product = Product.objects.get(pk=form_add.product_id)
        product.storage -= form.cleaned_data['quantity']

        def purchase_valid():
            if product.storage < form.cleaned_data['quantity'] and user.cash < form_add.total_cost:
                return True
            return False

        if purchase_valid():
            return redirect('purchase_error')

        user.save()
        product.save()
        return super().form_valid(form)


class PurchaseError(TemplateView):
    template_name = 'list/purchase_error.html'


class PurchaseList(ListView):
    model = Purchase
    context_object_name = 'purchases'
    template_name = 'list/purchase_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'return_form': ReturnForm
        })
        return context


class ReturnCreate(CreateView):
    success_url = '/purchase/list/'
    template_name = 'list/return_create.html'
    form_class = ReturnForm

    def form_valid(self, form):
        purchase_time = form.cleaned_data['purchase'].created_at
        contr_time = timezone.now() - timedelta(minutes=3)
        if purchase_time <= contr_time:
            return redirect("purchase_error")
        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect("purchase_error")

templates/authenticate/login.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign In">
        </form>

        <a href="{% url 'register' %}">Or register?</a>
    </div>
{% endblock %}

templates/authenticate/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/authenticate/register.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign Up">
        </form>

        <a href="{% url 'login' %}">Or login?</a>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(function () {
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1900:2020",
            });
        });
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My test shop</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"
            integrity="sha256-xI/qyl9vpwWFOXz7+x/9WkG5j/SVnSw21viy8fWwbeE="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
{% if request.user.is_authenticated %}
User:{{ user.username }} CASH : {{ user.cash }}

{% endif %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'list' %}">Start Page</a>
                </li>
            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                </li>
            {% else %}
                <a class="nav-link" href="{% url 'purchase_list' %}">Purchase List</a>
              {% if request.user.is_staff %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'product_create' %}">Product_create</a>
            </li>
             {% endif %}
                <li class="nav-item">

                    <a class="nav-link" href="{% url 'logout' %}">Sign Off</a>
                </li>

            {% endif %}
        </ul>
</nav>


{% block content %}
{% endblock %}

</body>
</html>
{% block scripts %}
{% endblock %}

templates/list/create.html
{% extends 'base.html' %}

{% block content %}

 <form action='.' method='POST'> {% csrf_token %}

	{{ form.as_p }}
	<input type='submit' value='Save' />

</form>
{% endblock %}

templates/list/index.html
{% extends 'base.html' %}

{% block content %}


        {% for goods in products %}

            {{ goods.title }} : {{ goods.price }}

                {% if request.user.is_authenticated %}
                <form  action="{% url 'purchase_create' goods.pk %}" method="post">
                        {% csrf_token %}
                        {{ buy_form }}
                    <input type="submit" value="Buy">
               </form>
                     {% if request.user.is_staff %}

{#                        <form  action="{% url 'product_update' goods.pk %}" method="post">#}
{#                        {% csrf_token %}#}
{#                    <input type="submit" value="Update">#}
{##}
{#               </form>#}


                    <a class="nav-link" href="{% url 'product_update' goods.pk %}">Update</a>
             {% endif %}

                    <br>
                {% endif %}

        {% endfor %}


        {% if object_list %}
            <div class="pagination" style="display: flex;
    justify-content: center;">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}

            </span>
            </div>
        {% endif %}



{% endblock %}

templates/list/note.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'note_update' object.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update note">
        </form>

{% endblock %}

templates/list/product_create.html
{% extends 'base.html' %}

{% block content %}

 <form action='.' method='POST'> {% csrf_token %}

	{{ form.as_p }}
	<input type='submit' value='Save' />

</form>
{% endblock %}

templates/list/product_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'product_update' object.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update product">
        </form>

{% endblock %}

templates/list/purchase_error.html
{% extends 'base.html' %}

{% block content %}

 <h1>This is impossible
 </h1>
{% endblock %}

templates/list/purchase_list.html
{% extends 'base.html' %}

{% block content %}

    {% for purchase in purchases %}
        {{ purchase.product.title }} <br> COUNT: {{ purchase.quantity }}, <br> TIME: {{ purchase.created_at }} <br>

        <form action="{% url 'return_create' %}" method="post">
            {% csrf_token %}

            <input type="hidden" name="purchase" required id="id_purchase" value="{{ purchase.pk }}">

            <input type="submit" value="Return">
        </form>
        <br>



    {% endfor %}
{% endblock %}

templates/list/return_create.html
<form action="{%  url 'purchase_list' %}" method="post">
{{ form }}
</form>